### ISSUE TITLE
newline?

### ISSUE THREAD

**Issue by mrc4tt** [parkervcp/parkertron#23]
Hi,
I did start with use your script via pterodactyl.

And I have a little issue, maybe you can come with a trick.
Is it possible to make it, so it's enter "newline" on the first line?

Example:
```
  keywords:
  - keyword: help
    reaction:
    - ""
    response:
    - &user& test\n\ntest //Here it should make a newline for the next text of test.
```
```
Example:
&user& test

test
```
