### ISSUE TITLE
error after add keyword: "help"

### ISSUE THREAD

**Issue by mrc4tt** [parkervcp/parkertron#32]
Hi.

When I try to add a "keyword" called: help.

What can I do for fix the "error", or do I need to ignore it?

As example output:
```
  keywords:
  - keyword: help
    reaction:
  - ""
    response:
    - "Do you need help? - Explain what your issue is. Remember to post server ID"
```

**Console output - this error I got:**
```
ERRO[0210] cannot unmarshal map[string]interface {} into Go struct field discordServer.ChanGroups of type string
ERRO[0210] cannot unmarshal map[string]interface {} into Go struct field discordServer.ChanGroups of type string
ERRO[0210] failed to unmarshal:
    github.com/goccy/go-yaml.Unmarshal
        /root/go/pkg/mod/github.com/goccy/go-yaml@v1.3.1/yaml.go:130
  - failed to decode value:
    github.com/goccy/go-yaml.(*Decoder).Decode
        /root/go/pkg/mod/github.com/goccy/go-yaml@v1.3.1/decode.go:1015
  - failed to decode value:
    github.com/goccy/go-yaml.(*Decoder).decodeStruct
        /root/go/pkg/mod/github.com/goccy/go-yaml@v1.3.1/decode.go:751
  - cannot unmarshal map[string]interface {} into Go struct field discordServer.ChanGroups of type string
```

**Comment by parkervcp** [comment]
The config should look like this 
```
  keywords:
  - keyword: help
    reaction:
    - ""
```

You can also just omit the reaction section.

**Comment by mrc4tt** [comment]
Are it normal that they will not always respond? eg: ``.test``
Sometimes ``example``doesn't respond. ;/ do I need to make "space" between commands/keyword(s)?

```
  commands:
  - command: test
    response:
    - This is a test
  commands:
  - command: panel
    response:
    - Panel are here >> test
  keywords:
  - keyword: example
    response:
    - I have responded to seeing the word example.
  keywords:
  - keyword: help
    response:
    - Hi &user&. Please elaborate on what your problem are and remember Support ID.
```

**Comment by parkervcp** [comment]
I am pretty sure you are overriding the previous commands section by having two of them. 
```
  commands:
  - command: test
    response:
    - This is a test
  - command: panel
    response:
    - Panel are here >> test
  keywords:
  - keyword: example
    response:
    - I have responded to seeing the word example.
  - keyword: help
    response:
    - Hi &user&. Please elaborate on what your problem are and remember Support ID.
```

**Comment by MikkelDK** [comment]
Hi, @parkervcp sorry for the tag anyway.

Is it possible for separate the "keywords/keyword" per channel?

For example - if someone type: "help" on testchannel, and it will respond with "Go to <#supportchannel>"
```
  - keyword: help
  - channels: <#test>
    response:
    - Hi &user&. Go to <#support> channel, please!
```
