### ISSUE TITLE
normal-user mention @staff-user

### ISSUE THREAD

**Issue by mrc4tt** [parkervcp/parkertron#33]
Hi.

Is it possible for the "bot" to automatically answer a "user" who is doing ``@user`` on the discord server?

As example:
user1: ``@mikkeldk, can you help me``
user2: ``can you help me please @mikkeldk``
BOT: ``@user1. No, he can't help you if you don't explain``

**Comment by MikkelDK** [comment]
Sorry, @parkervcp 

Are it's possible to make parkertron works with mention "specific" <@ID> e.g: ``<@249229859824467969>`` OR just ``@mikkeldk``

User1 typo: yo ``@mikkeldk`` help me.
BOT: ``random respond`` 

Example config setup:
```yaml
  keywords:
  - keyword: @mrc4t
    response:
    - "test"
  - keyword: <@249229859824467969>
    response:
    - "test"
```
