### ISSUE TITLE
Separate channel per keyword

### ISSUE THREAD

**Issue by mrc4tt** [parkervcp/parkertron#35]
Hi.

I have tried to figure about it's possible to set up a "separate" keyword for "per channel"

I would like to make, so "BOT" can't/don't respond to the keyword of ``test`` on channel2-id-here.

Do you have any idea?
```yml
channel_groups:
- channels:
  - channel-id-here
  - channel2-id-here
  mentions:
    ping:
      response:
      - "Please take your issue to the test channel"
    mention:
      response:
      - "Please take your issue to the test channel"
  keywords:
  - keyword: test
    response:
    - test
```

**Comment by parkervcp** [comment]
You need to create more than one channel group.

**Comment by mrc4tt** [comment]
So as example:
```yaml
channel_groups:
- channels:
  - channel2-id-here
  mentions:
    ping:
      response:
      - "Please take your issue to the test2 channel"
    mention:
      response:
      - "Please take your issue to the test2 channel"
  keywords:
  - keyword: test2
    response:
    - test2
channel_groups:
- channels:
  - channel1-id-here
  mentions:
    ping:
      response:
      - "Please take your issue to the test channel"
    mention:
      response:
      - "Please take your issue to the test channel"
  keywords:
  - keyword: test
    response:
    - test
```

**Comment by parkervcp** [comment]
That does look correct.

**Comment by mrc4tt** [comment]
Seems it doesn't read the lower channel_groups. with ``849961975248977941``
```bash
INFO[0282] channel groups [840204307411894302]
INFO[0282] file changed: /home/mikkel/bot/configs/discord/bot/bot/bot.yml
INFO[0282] channel groups [840204307411894302]
```

Config:
```yaml
channel_groups:
- channels:
  - 840204307411894302
 keywords:
  - keyword: test
    response:
    - yir
channel_groups:
- channels:
  - 849961975248977941
 keywords:
 - keyword: test
   response:
   - test
```

**Fixed**; I did just created a extra .yml file =)
