### ISSUE TITLE
Make BOT respond to picture/screenshot

### ISSUE THREAD

**Issue by mrc4tt** [parkervcp/parkertron#36]
I have tried and attach a screenshot or just pictures.
But the bot is only reacting with 👀.

How can I get BOT to respond to the screenshot? 
```yml
  parsing:
    image:
      filetypes:
      - png
      - jpg
```
