### ISSUE TITLE
Read whole keyword

### ISSUE THREAD

**Issue by mrc4tt** [parkervcp/parkertron#37]
Hi.

Are it's possible for BOT can read the "whole" keyword?

As example:
```yaml
  - keyword: bot
    response:
    - "test"
```

So if I write this word: ``bottom`` it should NOT answer that keyword. but only on the word "bot", so it ignores the word: "bottom" (i.e. tom)
