### ISSUE TITLE
Regex - help

### ISSUE THREAD

**Issue by ItJustFox** [parkervcp/parkertron#44]
Hello ! 
In my config i did make an config for a specific user using "eh"
![image](https://user-images.githubusercontent.com/42358087/185755213-db14d8f5-8e0a-4da0-85d6-fef32eb845ae.png)

But for some reson the bot respond to anything who got eh inside like **Bethlehem** or even the **behh** and not only to the eh, even in keyword, and using regex with () or other dont work, is there a way to only have the answer to "eh" and nothing else ? 
Or do we need use a specifique regex :x ?

**Comment by parkervcp** [comment]
1. `*` is a greedy regex.  You should check out regex101 to learn some more. This is an example of what you have there already. https://regex101.com/r/dnVqdM/1

2. There is a tag in the `keyword` type for exact matches.

Example:
```yaml
  keywords:
    - keyword: "hello"
      reaction:
        - "👋"
      response: 
        - "this is a response to the word 'hello'"
      exact: true
```
